import Head from "next/head";

import { api } from "@app/utils/api";
import { Callout, Container, Separator } from "@radix-ui/themes";
import HistoryTable from "@app/components/HistoryTable/HistoryTable";
import GenerateLinkCard from "@app/components/GenerateLinkCard/GenerateLinkCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container mt={"8"}>
        <GenerateLinkCard />

        <Separator my="3" size="4" />
        <Callout.Root>
          <Callout.Icon></Callout.Icon>
          <Callout.Text>
            The short links you create are accessible to everyone !
          </Callout.Text>
        </Callout.Root>
        <Separator my="3" size="4" />

        <HistoryTable />
      </Container>
    </>
  );
}
